#ifndef TINYSAT_INCLUDE_CORE_MACRO_HPP_
#define TINYSAT_INCLUDE_CORE_MACRO_HPP_

#ifdef TINYSAT_LOG_ENABLED
    #define TINYSAT_LOG(LEVEL, FORMAT, ...) \
        SPDLOG_##LEVEL(FORMAT, __VA_ARGS__) 
#else // TINYSAT_LOG_ENABLED
    #define TINYSAT_LOG(LEVEL, ...)
#endif // TINYSAT_LOG_ENABLED

#endif // TINYSAT_INCLUDE_CORE_MACRO_HPP_
